### ISSUE TITLE
Missing [] on help

### ISSUE THREAD

**Issue by macabeus** [GabrielaBezerra/CheckForChanges#1]
https://github.com/GabrielaBezerra/CheckForChanges/blob/a0d2f616492c769585c0bace8728ab5a50d89216/check-for-changes#L7

As the convention, we should to use `[]` to say that the `interval` is an optional parameter

**Comment by GabrielaBezerra** [comment]
Okay <3 thank you for pointing this.

**Comment by GabrielaBezerra** [comment]
Fixed at [commit f1651a3](https://github.com/GabrielaBezerra/CheckForChanges/commit/f1651a3e5c08f310a3a9d36617510f12962c009d) and [commit e79b7c1](https://github.com/GabrielaBezerra/CheckForChanges/commit/e79b7c1c3c1c268518e84aba5abfc941da53638c)
