### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by oliveira-julio** [GabrielaBezerra/CheckForChanges#2]
Hi :smile: .
figlet is a dependency.

**Comment by GabrielaBezerra** [comment]
YES! You're right! I forgot to mention that.

**Comment by GabrielaBezerra** [comment]
Fixed at [commit f1651a3](https://github.com/GabrielaBezerra/CheckForChanges/commit/f1651a3e5c08f310a3a9d36617510f12962c009d)
